# This is a basic workflow to demonstrate Gitops using Kong

name: Deploy to Kong on Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DECK_KONG_WORKSPACE: "${{ secrets.KONG_WORKSPACE }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Install Deck  
        run: |
          curl -sL https://github.com/Kong/deck/releases/download/v1.34.0/deck_1.34.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/
          
      - name: Check connectivity to Kong Control Plane
        run: |
          deck gateway ping --headers "kong-admin-token:${{ secrets.KONG_ADMIN_TOKEN }}" --kong-addr ${{ secrets.KONG_ADDR }} --tls-skip-verify
          
      - name: Validate the Declarative Config File
        run: |
          deck gateway validate --headers "kong-admin-token:${{ secrets.KONG_ADMIN_TOKEN }}" --kong-addr ${{ secrets.KONG_ADDR }} --tls-skip-verify kong/consumers kong/global-plugins kong/kong.yaml
          
      - name: View configuration drift
        run: |
          deck gateway diff --headers "kong-admin-token:${{ secrets.KONG_ADMIN_TOKEN }}" --kong-addr ${{ secrets.KONG_ADDR }} --tls-skip-verify kong/consumers kong/global-plugins kong/kong.yaml
          
      - name: Apply Configuration
        run: |
          deck gateway sync --headers "kong-admin-token:${{ secrets.KONG_ADMIN_TOKEN }}" --kong-addr ${{ secrets.KONG_ADDR }} --tls-skip-verify kong/consumers kong/global-plugins kong/kong.yaml
          
      
  
  
  
      
